version: 2

models:
  - name: mart_gh_cumulative
    description: cumulative count of stars
    columns:
      - name: repository
      - name: starred_at_month
      - name: sum_starscustomer_id
      - name: cumulative_stargazers

